# This file is part of Invenio.
#
#  Copyright (C) 2022 Graz University of Technology.
#
# React-Records-Marc21 is free software; you can redistribute it and/or
# modify it under the terms of the MIT License; see LICENSE file for more
# details.

name: Publish

on:
  push:
    tags:
      - v*

jobs:
  npm-publish-workflow:
    uses: tu-graz-library/.github/.github/workflows/npm-publish.yml@main
    secrets: inherit
